### PR TITLE
updating projects, adding governance and lead description

### PR DESCRIPTION
**Pull request by gati**
I added other projects that have leads, the new project template, and governance docs so other community members can edit.

### CODE REVIEW

**Comment by zachmueller** [comment]
Overall looks good. On the main README file, you refer to an #onboarding channel but I don't see that in the Slack. I think it'd be a good idea to have such a channel but want to make sure that's what you're referring to there.

**Comment by gati** [comment]
Good catch @zachmueller! Just added the channel in Slack.

**Comment by zachmueller** [comment]
Awesome, joined =)

I'm also curious what others' thoughts are on adding directly to the slack channels inside these README files? For example, the onboarding channel can be accessed like [#onboarding](https://datafordemocracy.slack.com/messages/onboarding/). Same would also work for linking to the individual users that are Project Leads/etc, i.e., could link to DM the person in Slack.

**Comment by gati** [comment]
That's a good idea - I'll update the README!

**Comment by zachmueller** [comment]
Cool, I think it looks good as a starter for getting the other content in the repo. There's some formatting stuff we can probably clean up / make more consistent in some of the additional files, but this looks like a good start! I'll merge it in.

**Pull request merged**
